### ISSUE TITLE
Unexpected token import

### ISSUE THREAD

**Issue by oskarrough** [hyphmongo/discography#1]
Hi, I'm excited to try this module, thanks for doing it!

But after running `npm install; npm run build; npm start` I see this:

```
> discography@0.0.1 start /Users/Oskar/Sites/discography
> node lib/index.js

/Users/Oskar/Sites/discography/knexfile.js:1
(function (exports, require, module, __filename, __dirname) { import path from 'path';
                                                              ^^^^^^

SyntaxError: Unexpected token import
```

Is it something with how babel is configured? I'm on node v8.11.2.

**Comment by oskarrough** [comment]
Changing the import to require in `knexfile.js` seems to solve it. For me at least.

**Comment by hyphmongo** [comment]
Thanks for submitting an issue! The file was missing from the babel transpilation, have moved it to the correct directory now. 

Let me know how you get on with the API and feel free to submit feature requests :)
